name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - uses: ncipollo/release-action@v1
    - name: Upload Release
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: test1
